### ISSUE TITLE
test1

### ISSUE THREAD

**Issue by petersopko** [petersopko/kodadot-bot-testing#1]

**Comment by petersopko** [comment]
I take this

**Comment by petersopko** [comment]
I'll take this

**Comment by petersopko** [comment]
I'll take this

**Comment by petersopko** [comment]
I'll take this

**Comment by petersopko** [comment]
I'll take this

**Comment by petersopko** [comment]
test

**Comment by petersopko** [comment]
I'll take this

**Comment by petersopko** [comment]
test

**Comment by petersopko** [comment]
test

**Comment by petersopko** [comment]
I take this

**Comment by petersopko** [comment]
ASSIGNED - @petersopko has been assigned with this issue. Task is locked 🔒 for 72 hours -> until 11/03/2022, 15:37:38

**Comment by petersopko** [comment]
I'll take this

**Comment by petersopko** [comment]
I'll take this

**Comment by petersopko** [comment]
I'll take this

**Comment by petersopko** [comment]
test

**Comment by petersopko** [comment]
I'll take this

**Comment by KodaBotTest** [comment]
ASSIGNED - @Codertocat has been assigned with this issue 🔒 Locked period expires in 3 hours at Wednesday, March 9th 2022, 13:35:38
